### ISSUE TITLE
Unable to install on Python 3.11

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/resample#165]
Hello Hans. When preparing scikit-hep 5.0.0 I went off and tried to check consistency of everything in docker, to be totally isolated from anything. All goes fine with Python 3.10,

`Successfully installed asdf-2.14.3 asdf-standard-1.0.3 asdf-transform-schemas-0.3.0 asdf-unit-schemas-0.1.0 attrs-22.2.0 awkward-2.0.8 awkward-cpp-9 boost-histogram-1.3.2 click-8.1.3 contourpy-1.0.7 cycler-0.11.0 decaylanguage-0.15.1 deprecated-1.2.13 fonttools-4.38.0 graphviz-0.20.1 hepstats-0.6.0 hepunits-2.3.1 hist-2.6.3 histoprint-2.4.0 iminuit-2.18.0 importlib-metadata-6.0.0 jmespath-1.0.1 jsonschema-4.17.3 kiwisolver-1.4.4 lark-1.1.5 matplotlib-3.7.0 mplhep-0.3.26 mplhep-data-0.0.3 numpy-1.24.2 packaging-23.0 pandas-1.5.3 particle-0.21.2 pillow-9.4.0 plumbum-1.8.1 pylhe-0.5.1 pyparsing-3.0.9 pyrsistent-0.19.3 python-dateutil-2.8.2 pytz-2022.7.1 pyyaml-6.0 resample-1.5.3 scikit-hep-5.0.0 scipy-1.10.1 semantic-version-2.10.0 six-1.16.0 tqdm-4.64.1 typing-extensions-4.5.0 uhi-0.3.3 uproot-5.0.3 vector-1.0.0 wrapt-1.15.0 zipp-3.15.0`

but I get an error with 3.11:

```
(venv) root@61f3fe7f1f91:/# python -m pip install git+https://github.com/scikit-hep/scikit-hep.git@eduardo-5.0.0
Collecting git+https://github.com/scikit-hep/scikit-hep.git@eduardo-5.0.0
  Cloning https://github.com/scikit-hep/scikit-hep.git (to revision eduardo-5.0.0) to /tmp/pip-req-build-qv2k08qb
  Running command git clone --filter=blob:none --quiet https://github.com/scikit-hep/scikit-hep.git /tmp/pip-req-build-qv2k08qb
  Running command git checkout -b eduardo-5.0.0 --track origin/eduardo-5.0.0
  Switched to a new branch 'eduardo-5.0.0'
  Branch 'eduardo-5.0.0' set up to track remote branch 'eduardo-5.0.0' from 'origin'.
  Resolved https://github.com/scikit-hep/scikit-hep.git to commit 160d4cbc55326070f5c56f24f6d0cd533f996d67
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting awkward~=2.0.0
  Using cached awkward-2.0.8-py3-none-any.whl (583 kB)
Collecting boost-histogram~=1.3.0
  Using cached boost_histogram-1.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
Collecting decaylanguage~=0.15.0
  Using cached decaylanguage-0.15.1-py3-none-any.whl (247 kB)
Collecting hepstats~=0.6.0
  Using cached hepstats-0.6.0-py3-none-any.whl (41 kB)
Collecting hepunits~=2.3.0
  Using cached hepunits-2.3.1-py3-none-any.whl (14 kB)
Collecting hist~=2.6.0
  Using cached hist-2.6.3-py3-none-any.whl (36 kB)
Collecting histoprint~=2.4.0
  Using cached histoprint-2.4.0-py3-none-any.whl (16 kB)
Collecting iminuit~=2.18.0
  Using cached iminuit-2.18.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (377 kB)
Collecting matplotlib>2.0.0
  Using cached matplotlib-3.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Collecting mplhep~=0.3.0
  Using cached mplhep-0.3.26-py3-none-any.whl (34 kB)
Requirement already satisfied: numpy>=1.13.1 in /root/venv/lib/python3.11/site-packages (from scikit-hep==5.0.0) (1.24.2)
Collecting particle~=0.21.0
  Using cached particle-0.21.2-py3-none-any.whl (262 kB)
Collecting pylhe~=0.5.0
  Using cached pylhe-0.5.1-py3-none-any.whl (11 kB)
Collecting resample~=1.5.0
  Using cached resample-1.5.3.tar.gz (268 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/root/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-57lublz3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-57lublz3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-57lublz3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

This is not a problem for me right now as at the moment not all dependencies of scikit-hep support 3.11 (to be checked, actually, with latest releases), hence I do not need support on the day, but I thought I would let you know. I did not investigate further. Maybe the issue is trivial and/or known to you?

**Comment by HDembinski** [comment]
This should be solved now. I am testing on 3.11 now and its works. Since random-table code is now in scipy, I don't have to compile a C-extension anymore either and thus can provide universal wheels.
